#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════
# Dream Planet Referral Campaign — Canonical Master Build
#
# Regenerates DreamPlanet_Master_v1(.mp4|_audio.mp4|_no_audio.mp4) from the
# authoritative scene sources listed below. Replaces ad-hoc/manual FFmpeg
# commands with a single deterministic, rerunnable pipeline.
#
# See MASTER_BUILD.md (same directory) for full documentation, including
# how to add Scene 5 / Scene 6 and troubleshooting for missing assets.
#
# Usage:
#   ./build_master.sh                 # writes final deliverables into this directory
#   ./build_master.sh /path/to/dir    # writes final deliverables into an alternate
#                                      # directory instead (use this to verify a
#                                      # rebuild without touching approved masters)
# ══════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../../../.." && pwd)"

# ── Output location ─────────────────────────────────────────────────────────
# Defaults to this directory (the real Final Edit deliverables). Pass an
# argument to redirect output elsewhere, e.g. to sanity-check a rebuild
# before ever touching the approved DreamPlanet_Master_v1* files.
OUT_DIR="${1:-$SCRIPT_DIR}"
mkdir -p "$OUT_DIR"

# ── Build workspace ──────────────────────────────────────────────────────────
# All intermediate/normalized clips go here. This directory is fully
# regenerated by this script on every run — nothing outside it is relied on
# except the authoritative sources declared below, and nothing here is a
# deliverable. Safe to delete between runs.
WORK="$REPO_ROOT/tmp_dp_master_build"
rm -rf "$WORK"
mkdir -p "$WORK"

echo "Repo root:   $REPO_ROOT"
echo "Work dir:    $WORK"
echo "Output dir:  $OUT_DIR"
echo ""

# ── Authoritative sources ────────────────────────────────────────────────────
# Scene 1 & Scene 2 are procedurally rendered (ken-burns zoom + text + light
# streak) from the locked hero frame — there is no flat "scene1.mp4" source
# to point at, so their authoritative inputs are the assets below plus the
# render logic in build_scene1()/build_scene2().
S1_LOCKED="$REPO_ROOT/extracted_scenes/Scene1scene2_contents/Dre-animation/Dream Planet Referral Campaign/Scene 1 (LOCKED)"
S2_DIR="$REPO_ROOT/extracted_scenes/Scene1scene2_contents/Dre-animation/Dream Planet Referral Campaign/Scene 2"
MASTER_FRAME="$S1_LOCKED/Final Master Frame/scene1_master_frame.jpg"
FONT="$S1_LOCKED/Project Files/fonts/Inter-SemiBold.ttf"
DP_ICON="$S2_DIR/Project Files/assets/dp_icon.png"

# Scene 3 & Scene 4 are flat authoritative video files.
SCENE3_SRC="$REPO_ROOT/extracted_scenes/Scene3Scene4_contents/Scene1scene2_contents/Dre-animation/Dream Planet Referral Campaign/Scene 3/Final Animation/scene3_final.mp4"
SCENE4_SRC="$REPO_ROOT/extracted_scenes/Scene3Scene4_contents/Scene1scene2_contents/Dre-animation/Dream Planet Referral Campaign/Scene 4/Final Animation/scene4_final.mp4"

# Campaign music — single continuous track applied at the master level only.
MUSIC="$REPO_ROOT/extracted_scenes/Scene3Scene4_contents/Replit-Design-Project/attached_assets/Ai_music_for_dream_planet_video__1785842118219.mp3"

# ── Scene 3 trim guard ───────────────────────────────────────────────────────
# scene3_final.mp4 has ~3.0s of blank/white content baked in before the
# Referral Home UI appears. A previous build concatenated it untrimmed and
# shipped a ~2.9s dead white screen right after Scene 2 (fixed once already —
# see replit.md "Final master QA"). This constant, plus the automated
# brightness check in build_scene3(), is what prevents that regressing.
SCENE3_TRIM_START=3.0

# Required final output spec.
TARGET_W=1080
TARGET_H=1920
TARGET_FPS=30

# ── Scene order (editable) ───────────────────────────────────────────────────
# To add Scene 5 / Scene 6: write a build_scene5()/build_scene6() function
# below following the same contract as the existing ones (produce
# "$WORK/<name>_normalized.mp4" at ${TARGET_W}x${TARGET_H}, ${TARGET_FPS}fps,
# h264/yuv420p, no audio), then append the name here. See MASTER_BUILD.md.
SCENE_ORDER=(scene1 scene2 scene3 scene4)

# ══════════════════════════════════════════════════════════════════════════
# Scene builders — each produces "$WORK/<scene>_normalized.mp4"
# ══════════════════════════════════════════════════════════════════════════

prepare_generated_assets() {
  echo "── Preparing Scene 1/2 procedural assets ──"
  ffmpeg -y -i "$MASTER_FRAME" -vf "scale=1640:1980" -q:v 2 -update 1 \
    "$WORK/hero_9x16.jpg" -loglevel warning

  ffmpeg -y -f lavfi -i "color=c=black:s=${TARGET_W}x${TARGET_H}:r=1" \
    -vf "format=rgba,geq=r=255:g=248:b=232:a='clip(150*exp(-0.5*pow(((X-540)*cos(0.38397)-(Y-960)*sin(0.38397))/172.8\,2))\,0\,255)'" \
    -vframes 1 -update 1 "$WORK/streak_s1_1920.png" -loglevel warning

  ffmpeg -y -f lavfi -i "color=c=black:s=${TARGET_W}x${TARGET_H}:r=1" \
    -vf "format=rgba,geq=r=255:g=250:b=238:a='clip(78*exp(-0.5*pow(((X-594)*cos(0.31416)-(Y-768)*sin(0.31416))/81\,2))\,0\,255)'" \
    -vframes 1 -update 1 "$WORK/streak_s2_1920.png" -loglevel warning
  echo "  done"
}

build_scene1() {
  echo "── Building Scene 1 (0.0–3.0s, generated) ──"
  ffmpeg -y \
    -loop 1 -i "$WORK/hero_9x16.jpg" \
    -i "$WORK/streak_s1_1920.png" \
    -filter_complex "
      [0:v]scale=w='trunc(iw*(1+0.065*min(1,max(0,(t-0.5)/2.5)))/2)*2':h='trunc(ih*(1+0.065*min(1,max(0,(t-0.5)/2.5)))/2)*2':eval=frame[zoomed];
      [zoomed]crop=w=${TARGET_W}:h=${TARGET_H}:x='(iw-${TARGET_W})/2':y='(ih-${TARGET_H})/2'[cropped];
      [1:v]format=rgba[streak];
      [cropped][streak]overlay=x='-1080+(t-0.8)/1.5*2160':y=0:enable='between(t,0.8,2.3)'[lit];
      [lit]drawtext=fontfile='$FONT':text='More than followers.':fontsize=54:fontcolor=white:shadowcolor=black@0.55:shadowx=2:shadowy=3:x=90:y=h-th-160:alpha='if(lt(t,1.2),0,if(lt(t,1.6),(t-1.2)/0.4,if(lt(t,2.8),1,if(lt(t,3.0),(3.0-t)/0.2,0))))'[texted];
      [texted]fade=t=in:st=0.2:d=0.3:color=black,setsar=1[vout]
    " \
    -map "[vout]" \
    -t 3.0 -r "$TARGET_FPS" \
    -c:v libx264 -preset medium -crf 14 -pix_fmt yuv420p \
    "$WORK/scene1_normalized.mp4" \
    -loglevel warning
  echo "  done"
}

build_scene2() {
  echo "── Building Scene 2 (3.0–6.0s, generated) ──"
  ffmpeg -y \
    -loop 1 -i "$WORK/hero_9x16.jpg" \
    -i "$WORK/streak_s2_1920.png" \
    -i "$DP_ICON" \
    -filter_complex "
      [0:v]scale=w='trunc(iw*(1.065+0.035*min(1,max(0,t/3.0)))/2)*2':h='trunc(ih*(1.065+0.035*min(1,max(0,t/3.0)))/2)*2':eval=frame[zoomed];
      [zoomed]crop=w=${TARGET_W}:h=${TARGET_H}:x='(iw-${TARGET_W})/2':y='(ih-${TARGET_H})/2'[cropped];
      [cropped]eq=contrast='1+0.018*min(1,max(0,(t-0.6)/0.6))':eval=frame[graded];
      [1:v]format=rgba[streak];
      [graded][streak]overlay=x='-90+(t-1.5)/0.8*180':y='-30+(t-1.5)/0.8*60':enable='between(t,1.5,2.3)'[lit];
      [2:v]scale=-2:96,format=rgba[iconraw];
      [iconraw]fade=t=in:st=2.2:d=0.5:alpha=1[iconfaded];
      [lit][iconfaded]overlay=x=90:y=1542:enable='gte(t,2.2)'[iconned];
      [iconned]drawtext=fontfile='$FONT':text='Join me on':fontsize=40:fontcolor=white:shadowcolor=black@0.5:shadowx=1:shadowy=2:x=90:y=1660:alpha='if(lt(t,0.6),0,if(lt(t,1.0),(t-0.6)/0.4,if(lt(t,2.5),1,if(lt(t,2.8),(2.8-t)/0.3,0))))'[t1];
      [t1]drawtext=fontfile='$FONT':text='Dream ':fontsize=82:fontcolor=white:shadowcolor=black@0.55:shadowx=2:shadowy=3:x=90:y=1709:alpha='if(lt(t,1.0),0,if(lt(t,1.4),(t-1.0)/0.4,if(lt(t,2.5),1,if(lt(t,2.8),(2.8-t)/0.3,0))))'[t2];
      [t2]drawtext=fontfile='$FONT':text='Planet':fontsize=82:fontcolor=0xF64A01:shadowcolor=black@0.55:shadowx=2:shadowy=3:x=374:y=1709:alpha='if(lt(t,1.0),0,if(lt(t,1.4),(t-1.0)/0.4,if(lt(t,2.5),1,if(lt(t,2.8),(2.8-t)/0.3,0))))',setsar=1[vout]
    " \
    -map "[vout]" \
    -t 3.0 -r "$TARGET_FPS" \
    -c:v libx264 -preset medium -crf 14 -pix_fmt yuv420p \
    "$WORK/scene2_normalized.mp4" \
    -loglevel warning
  echo "  done"
}

build_scene3() {
  echo "── Building Scene 3 (trim blank intro @ ss=${SCENE3_TRIM_START}, normalize) ──"
  local src_dur
  src_dur=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$SCENE3_SRC")
  if (( $(echo "$SCENE3_TRIM_START >= $src_dur" | bc -l) )); then
    echo "ERROR: SCENE3_TRIM_START (${SCENE3_TRIM_START}s) >= scene3_final.mp4 duration (${src_dur}s)." >&2
    echo "       scene3_final.mp4 may have been re-exported without its blank intro; verify the source before adjusting this constant." >&2
    exit 1
  fi

  ffmpeg -y -ss "$SCENE3_TRIM_START" -i "$SCENE3_SRC" \
    -vf "fps=${TARGET_FPS},scale=${TARGET_W}:${TARGET_H},setsar=1" \
    -c:v libx264 -preset medium -crf 14 -pix_fmt yuv420p -an \
    "$WORK/scene3_normalized.mp4" \
    -loglevel warning

  # Guard: the whole reason this trim exists is to cut scene3_final.mp4's
  # blank/white opening. If the resulting first frame is still near-blank
  # white, the trim point (or the source) has drifted — fail loudly instead
  # of silently shipping the bug again.
  ffmpeg -y -i "$WORK/scene3_normalized.mp4" -vf "select=eq(n\,0)" -frames:v 1 -update 1 \
    "$WORK/scene3_first_frame.png" -loglevel warning
  local brightness
  brightness=$(convert "$WORK/scene3_first_frame.png" -colorspace Gray -format "%[fx:mean]" info: 2>/dev/null || echo "0")
  if (( $(echo "$brightness > 0.95" | bc -l) )); then
    echo "ERROR: Scene 3's first frame after trimming is still near-blank white (mean brightness ${brightness})." >&2
    echo "       The blank-intro bug may have regressed — do not ship this build. Inspect $WORK/scene3_first_frame.png." >&2
    exit 1
  fi
  echo "  done (first-frame brightness check passed: ${brightness})"
}

build_scene4() {
  echo "── Building Scene 4 (normalize) ──"
  ffmpeg -y -i "$SCENE4_SRC" \
    -vf "fps=${TARGET_FPS},scale=${TARGET_W}:${TARGET_H},setsar=1" \
    -c:v libx264 -preset medium -crf 14 -pix_fmt yuv420p -an \
    "$WORK/scene4_normalized.mp4" \
    -loglevel warning
  echo "  done"
}

# ══════════════════════════════════════════════════════════════════════════
# Assemble
# ══════════════════════════════════════════════════════════════════════════

prepare_generated_assets
for scene in "${SCENE_ORDER[@]}"; do
  "build_${scene}"
done

echo ""
echo "── Concatenating scenes in order: ${SCENE_ORDER[*]} ──"
FFMPEG_INPUTS=()
FILTER=""
LABELS=""
i=0
for scene in "${SCENE_ORDER[@]}"; do
  FFMPEG_INPUTS+=(-i "$WORK/${scene}_normalized.mp4")
  FILTER+="[$i:v]setsar=1:1[v$i];"
  LABELS+="[v$i]"
  i=$((i + 1))
done
FILTER+="${LABELS}concat=n=${#SCENE_ORDER[@]}:v=1:a=0[vout]"

ffmpeg -y "${FFMPEG_INPUTS[@]}" \
  -filter_complex "$FILTER" \
  -map "[vout]" \
  -c:v libx264 -preset medium -crf 14 -pix_fmt yuv420p \
  "$WORK/master_no_audio.mp4" \
  -loglevel warning

MASTER_DUR=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$WORK/master_no_audio.mp4")
echo "  done → master_no_audio.mp4 (duration: ${MASTER_DUR}s)"

echo ""
echo "── Applying campaign music (master level only) ──"
FADE_START=$(echo "$MASTER_DUR - 1.0" | bc)
ffmpeg -y \
  -i "$WORK/master_no_audio.mp4" \
  -i "$MUSIC" \
  -filter_complex "[1:a]atrim=0:${MASTER_DUR},afade=t=out:st=${FADE_START}:d=1.0[afinal]" \
  -map "0:v" -map "[afinal]" \
  -c:v copy -c:a aac -b:a 192k \
  "$WORK/master_with_audio.mp4" \
  -loglevel warning
echo "  done → master_with_audio.mp4"

# ══════════════════════════════════════════════════════════════════════════
# Validation
# ══════════════════════════════════════════════════════════════════════════
echo ""
echo "── Validating build ──"
FAIL=0

probe_video() { ffprobe -v error -select_streams v:0 -show_entries stream="$1" -of default=noprint_wrappers=1:nokey=1 "$2"; }
probe_format() { ffprobe -v error -show_entries format="$1" -of default=noprint_wrappers=1:nokey=1 "$2"; }

FINAL_W=$(probe_video width "$WORK/master_with_audio.mp4")
FINAL_H=$(probe_video height "$WORK/master_with_audio.mp4")
FINAL_FPS=$(probe_video r_frame_rate "$WORK/master_with_audio.mp4")
FINAL_VDUR=$(probe_format duration "$WORK/master_with_audio.mp4")
HAS_AUDIO=$(ffprobe -v error -select_streams a -show_entries stream=codec_type -of csv=p=0 "$WORK/master_with_audio.mp4" || true)
AUDIO_DUR=$(ffprobe -v error -select_streams a:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 "$WORK/master_with_audio.mp4")

check() {
  local desc="$1" ok="$2"
  if [[ "$ok" == "1" ]]; then echo "  [PASS] $desc"; else echo "  [FAIL] $desc"; FAIL=1; fi
}

check "resolution is ${TARGET_W}x${TARGET_H} (got ${FINAL_W}x${FINAL_H})" \
  "$([[ "$FINAL_W" == "$TARGET_W" && "$FINAL_H" == "$TARGET_H" ]] && echo 1 || echo 0)"
check "frame rate is ${TARGET_FPS}/1 (got ${FINAL_FPS})" \
  "$([[ "$FINAL_FPS" == "${TARGET_FPS}/1" ]] && echo 1 || echo 0)"
check "audio stream present" \
  "$([[ "$HAS_AUDIO" == "audio" ]] && echo 1 || echo 0)"
check "audio duration (${AUDIO_DUR}s) matches video duration (${FINAL_VDUR}s) within 0.2s" \
  "$(awk -v a="$AUDIO_DUR" -v b="$FINAL_VDUR" 'BEGIN{d=a-b; if(d<0)d=-d; print (d<0.2)?1:0}')"

# Scene ordering / completeness: sum of each normalized scene's own duration
# must match the concatenated (pre-audio) master duration. If a scene were
# skipped, duplicated, or reordered in a way that changed total length,
# this catches it.
SUM=0
TIMELINE=""
CURSOR=0
for scene in "${SCENE_ORDER[@]}"; do
  d=$(probe_format duration "$WORK/${scene}_normalized.mp4")
  SUM=$(echo "$SUM + $d" | bc)
  END=$(echo "$CURSOR + $d" | bc)
  TIMELINE+="$(printf "    %-8s %6.2fs - %6.2fs  (%.2fs)" "$scene" "$CURSOR" "$END" "$d")"$'\n'
  CURSOR=$END
done
check "scene ordering/completeness: sum of scene durations (${SUM}s) matches master (${MASTER_DUR}s) within 0.05s" \
  "$(awk -v a="$SUM" -v b="$MASTER_DUR" 'BEGIN{d=a-b; if(d<0)d=-d; print (d<0.05)?1:0}')"

if [[ "$FAIL" != "0" ]]; then
  echo ""
  echo "Validation FAILED — deliverables were still generated in $WORK but were NOT copied to $OUT_DIR." >&2
  exit 1
fi

# ══════════════════════════════════════════════════════════════════════════
# Deliverables
# ══════════════════════════════════════════════════════════════════════════
cp "$WORK/master_no_audio.mp4"   "$OUT_DIR/DreamPlanet_Master_v1_no_audio.mp4"
cp "$WORK/master_with_audio.mp4" "$OUT_DIR/DreamPlanet_Master_v1_audio.mp4"
cp "$WORK/master_with_audio.mp4" "$OUT_DIR/DreamPlanet_Master_v1.mp4"

echo ""
echo "══════════════════════════════════════════════════════"
echo " BUILD REPORT"
echo "══════════════════════════════════════════════════════"
echo "  Resolution:      ${FINAL_W}x${FINAL_H}"
echo "  Frame rate:      ${FINAL_FPS}"
echo "  Video duration:  ${FINAL_VDUR}s"
echo "  Audio duration:  ${AUDIO_DUR}s"
echo "  Scene order:     ${SCENE_ORDER[*]}"
echo "  Timeline:"
echo -n "$TIMELINE"
echo "  Deliverables written to: $OUT_DIR"
echo "    - DreamPlanet_Master_v1.mp4"
echo "    - DreamPlanet_Master_v1_audio.mp4"
echo "    - DreamPlanet_Master_v1_no_audio.mp4"
echo "══════════════════════════════════════════════════════"
