#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# Dream Planet Referral Campaign — Master Build Validator
#
# Standalone validation script. Exits 0 on full pass, 1 on any failure.
# CI/pre-push ready: no interaction required, clean pass/fail output.
#
# Two modes:
#   QUICK (default) — probes the existing approved masters + source assets.
#                     Fast (~5s). Use for pre-push hooks and CI.
#   FULL            — invokes build_master.sh to a temp dir, then probes the
#                     rebuilt output. Slower (~60s). Use before releasing a
#                     new approved master.
#
# Usage:
#   ./validate_master.sh                    # quick mode (probe existing files)
#   ./validate_master.sh --full             # full rebuild + validate
#   ./validate_master.sh --full --out /dir  # full rebuild, write output to /dir
#   ./validate_master.sh --help
#
# Exit codes:
#   0  — all checks passed
#   1  — one or more checks failed
#   2  — usage error / prerequisite missing
#
# Extensibility: when Scene 5 or Scene 6 is added, see the "SCENE REGISTRY"
# section below — that is the only section that needs updating.
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../../../.." && pwd)"

# ── Defaults ──────────────────────────────────────────────────────────────────
MODE="quick"
FULL_OUT_DIR=""
VERBOSE=0

# ── Argument parsing ──────────────────────────────────────────────────────────
usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Options:
  --quick          Probe existing approved masters and source assets (default, ~5s)
  --full           Rebuild to temp dir via build_master.sh, then validate (~60s)
  --out DIR        Output dir for --full rebuild (default: auto temp dir)
  --verbose        Print per-check detail even on pass
  --help           Show this message

Exit codes: 0 = all pass, 1 = validation failure, 2 = usage/prereq error
EOF
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --quick)   MODE="quick"; shift ;;
    --full)    MODE="full";  shift ;;
    --out)     FULL_OUT_DIR="$2"; shift 2 ;;
    --verbose) VERBOSE=1;   shift ;;
    --help|-h) usage ;;
    *) echo "Unknown option: $1" >&2; usage ;;
  esac
done

# ── Prerequisites ─────────────────────────────────────────────────────────────
for tool in ffprobe ffmpeg convert bc; do
  if ! command -v "$tool" &>/dev/null; then
    echo "ERROR: Required tool not found: $tool" >&2
    echo "       Install ffmpeg (includes ffprobe) and imagemagick (for convert)." >&2
    exit 2
  fi
done

# ══════════════════════════════════════════════════════════════════════════════
# SCENE REGISTRY
# ──────────────────────────────────────────────────────────────────────────────
# When adding Scene 5 or Scene 6:
#
#   1. Add a SCENE5_SRC variable below pointing to the authoritative source.
#   2. For flat video scenes: add an entry in FLAT_SCENE_SRCS.
#      For procedural scenes (generated by FFmpeg like S1/S2): add the new
#      asset paths to PROC_ASSETS instead.
#   3. Add the scene name to SCENE_ORDER.
#   4. If the new scene needs a blank-intro trim guard (like Scene 3), add an
#      entry to TRIM_GUARDS: TRIM_GUARDS[sceneN]="<trim_start_seconds>".
#   5. Adjust MIN_DURATION / MAX_DURATION if the total length changes.
#
# Nothing else in this script needs to change.
# ══════════════════════════════════════════════════════════════════════════════

# ── Scene order ───────────────────────────────────────────────────────────────
SCENE_ORDER=(scene1 scene2 scene3 scene4)

# ── Flat video sources (scenes whose source is a pre-rendered .mp4) ───────────
S2_BASE="$REPO_ROOT/extracted_scenes/Scene1scene2_contents/Dre-animation/Dream Planet Referral Campaign"
S34_BASE="$REPO_ROOT/extracted_scenes/Scene3Scene4_contents/Scene1scene2_contents/Dre-animation/Dream Planet Referral Campaign"

declare -A FLAT_SCENE_SRCS
FLAT_SCENE_SRCS[scene3]="$S34_BASE/Scene 3/Final Animation/scene3_final.mp4"
FLAT_SCENE_SRCS[scene4]="$S34_BASE/Scene 4/Final Animation/scene4_final.mp4"

# ── Procedural scene assets (scenes 1 & 2 are generated from these) ───────────
S1_LOCKED="$S2_BASE/Scene 1 (LOCKED)"
PROC_ASSETS=(
  "$S1_LOCKED/Final Master Frame/scene1_master_frame.jpg"
  "$S1_LOCKED/Project Files/fonts/Inter-SemiBold.ttf"
  "$S2_BASE/Scene 2/Project Files/assets/dp_icon.png"
)

# ── Trim guards (scene → trim_start_seconds) ──────────────────────────────────
# Scenes listed here must pass a first-frame brightness check after trimming.
declare -A TRIM_GUARDS
TRIM_GUARDS[scene3]="3.0"

# ── Campaign music ────────────────────────────────────────────────────────────
MUSIC="$REPO_ROOT/extracted_scenes/Scene3Scene4_contents/Replit-Design-Project/attached_assets/Ai_music_for_dream_planet_video__1785842118219.mp3"

# ── Approved masters location ─────────────────────────────────────────────────
MASTERS_DIR="$SCRIPT_DIR"

# ── Expected output spec ──────────────────────────────────────────────────────
TARGET_W=1080
TARGET_H=1920
TARGET_FPS=30

# Duration bounds (seconds). Update when adding scenes that change total length.
MIN_DURATION=15.0
MAX_DURATION=120.0

# Tolerances
AUDIO_VIDEO_TOLERANCE=0.5    # seconds: audio duration vs video duration
DURATION_SCENE_SUM_TOLERANCE=0.1  # seconds: sum-of-scenes vs master duration

# First-frame brightness threshold for trim guards (0.0–1.0; fail if above)
BRIGHTNESS_THRESHOLD=0.95

# ══════════════════════════════════════════════════════════════════════════════
# Helpers
# ══════════════════════════════════════════════════════════════════════════════

PASS=0
FAIL=0
FAILURES=()

_pass() { PASS=$((PASS+1)); [[ "$VERBOSE" == "1" ]] && echo "  [PASS] $1"; }
_fail() { FAIL=$((FAIL+1)); FAILURES+=("$1"); echo "  [FAIL] $1"; }
_info() { echo "  [INFO] $1"; }

probe_video()  { ffprobe -v error -select_streams v:0 -show_entries stream="$1" -of default=noprint_wrappers=1:nokey=1 "$2" 2>/dev/null; }
probe_format() { ffprobe -v error -show_entries format="$1" -of default=noprint_wrappers=1:nokey=1 "$2" 2>/dev/null; }
probe_audio()  { ffprobe -v error -select_streams a -show_entries stream=codec_type -of csv=p=0 "$1" 2>/dev/null; }

within_tolerance() {
  # Returns 1 if |a - b| <= tol, 0 otherwise
  awk -v a="$1" -v b="$2" -v tol="$3" 'BEGIN{d=a-b; if(d<0)d=-d; print (d<=tol)?1:0}'
}
gt() { awk -v a="$1" -v b="$2" 'BEGIN{print (a>b)?1:0}'; }
lt() { awk -v a="$1" -v b="$2" 'BEGIN{print (a<b)?1:0}'; }

# ══════════════════════════════════════════════════════════════════════════════
# Full-rebuild mode: invoke build_master.sh, then set MASTERS_DIR to output
# ══════════════════════════════════════════════════════════════════════════════

if [[ "$MODE" == "full" ]]; then
  if [[ -z "$FULL_OUT_DIR" ]]; then
    FULL_OUT_DIR="$(mktemp -d /tmp/dp_validate_XXXXXX)"
    echo "Full rebuild mode — output dir: $FULL_OUT_DIR"
    _CLEANUP_OUT=1
  else
    mkdir -p "$FULL_OUT_DIR"
    echo "Full rebuild mode — output dir: $FULL_OUT_DIR"
    _CLEANUP_OUT=0
  fi

  echo ""
  echo "── Running build_master.sh ──────────────────────────────────────────────────"
  if bash "$SCRIPT_DIR/build_master.sh" "$FULL_OUT_DIR"; then
    echo "── build_master.sh finished ─────────────────────────────────────────────────"
  else
    echo ""
    echo "ERROR: build_master.sh exited with an error. Validation aborted." >&2
    [[ "${_CLEANUP_OUT:-0}" == "1" ]] && rm -rf "$FULL_OUT_DIR"
    exit 1
  fi

  MASTERS_DIR="$FULL_OUT_DIR"
  echo ""
fi

# ══════════════════════════════════════════════════════════════════════════════
# Validation suite
# ══════════════════════════════════════════════════════════════════════════════

echo "══════════════════════════════════════════════════════════════════════════════"
echo " DREAM PLANET MASTER BUILD — VALIDATION"
echo " Mode:        ${MODE^^}"
echo " Masters dir: $MASTERS_DIR"
echo "══════════════════════════════════════════════════════════════════════════════"
echo ""

# ── Section 1: Source assets ──────────────────────────────────────────────────
echo "── [1/5] Source assets ──────────────────────────────────────────────────────"

# Procedural assets (S1/S2)
for asset in "${PROC_ASSETS[@]}"; do
  name="$(basename "$asset")"
  if [[ -f "$asset" && -s "$asset" ]]; then
    _pass "Procedural asset exists and non-empty: $name"
  else
    _fail "Procedural asset missing or empty: $asset"
  fi
done

# Flat video sources
for scene in "${SCENE_ORDER[@]}"; do
  if [[ -v "FLAT_SCENE_SRCS[$scene]" ]]; then
    src="${FLAT_SCENE_SRCS[$scene]}"
    name="$(basename "$src")"
    if [[ -f "$src" && -s "$src" ]]; then
      # Probe it with ffprobe to verify it's a readable video file
      if ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$src" &>/dev/null; then
        dur=$(probe_format duration "$src")
        _pass "$name exists and is readable (${dur}s)"
      else
        _fail "$name exists but ffprobe cannot read it: $src"
      fi
    else
      _fail "$name missing or empty: $src"
    fi
  fi
done

# Music
music_name="$(basename "$MUSIC")"
if [[ -f "$MUSIC" && -s "$MUSIC" ]]; then
  _pass "Music track exists and non-empty: $music_name"
else
  _fail "Music track missing or empty: $MUSIC"
fi

echo ""

# ── Section 2: Master deliverables exist and are playable ─────────────────────
echo "── [2/5] Master deliverables — existence and playability ────────────────────"

MASTER_AUDIO="$MASTERS_DIR/DreamPlanet_Master_v1_audio.mp4"
MASTER_NO_AUDIO="$MASTERS_DIR/DreamPlanet_Master_v1_no_audio.mp4"
MASTER_COMBINED="$MASTERS_DIR/DreamPlanet_Master_v1.mp4"

for label_path in \
    "DreamPlanet_Master_v1_audio.mp4:$MASTER_AUDIO" \
    "DreamPlanet_Master_v1_no_audio.mp4:$MASTER_NO_AUDIO" \
    "DreamPlanet_Master_v1.mp4:$MASTER_COMBINED"; do
  label="${label_path%%:*}"
  path="${label_path#*:}"
  if [[ ! -f "$path" || ! -s "$path" ]]; then
    _fail "$label missing or empty: $path"
    continue
  fi
  if ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$path" &>/dev/null; then
    _pass "$label exists and is playable ($(probe_format size "$path") bytes)"
  else
    _fail "$label exists but ffprobe cannot read it — file may be corrupt: $path"
  fi
done

echo ""

# ── Section 3: Video spec — resolution, frame rate, duration ─────────────────
echo "── [3/5] Video spec — resolution, frame rate, duration ──────────────────────"

if [[ -f "$MASTER_AUDIO" ]]; then
  FINAL_W=$(probe_video width "$MASTER_AUDIO")
  FINAL_H=$(probe_video height "$MASTER_AUDIO")
  FINAL_FPS=$(probe_video r_frame_rate "$MASTER_AUDIO")
  FINAL_DUR=$(probe_format duration "$MASTER_AUDIO")

  # Resolution — must be at least TARGET_W × TARGET_H in 9:16 orientation
  if [[ "$FINAL_W" == "$TARGET_W" && "$FINAL_H" == "$TARGET_H" ]]; then
    _pass "Resolution is ${TARGET_W}×${TARGET_H} (got ${FINAL_W}×${FINAL_H})"
  elif [[ "$(gt "$FINAL_W" "0")" == "1" && "$(gt "$FINAL_H" "0")" == "1" ]]; then
    # Check 9:16 aspect ratio (width/height ≈ 0.5625, tolerance ±0.01)
    RATIO=$(awk -v w="$FINAL_W" -v h="$FINAL_H" 'BEGIN{printf "%.4f", w/h}')
    IS_916=$(awk -v r="$RATIO" 'BEGIN{d=r-0.5625; if(d<0)d=-d; print (d<0.01)?1:0}')
    W_OK=$(awk -v w="$FINAL_W" -v tw="$TARGET_W" 'BEGIN{print (w>=tw)?1:0}')
    if [[ "$IS_916" == "1" && "$W_OK" == "1" ]]; then
      _pass "Resolution ${FINAL_W}×${FINAL_H} is ≥${TARGET_W}p in 9:16 ratio"
    else
      _fail "Resolution ${FINAL_W}×${FINAL_H} — expected ${TARGET_W}×${TARGET_H} (9:16); ratio=${RATIO}"
    fi
  else
    _fail "Could not read resolution from $MASTER_AUDIO"
  fi

  # Frame rate
  if [[ "$FINAL_FPS" == "${TARGET_FPS}/1" ]]; then
    _pass "Frame rate is ${TARGET_FPS}fps (got ${FINAL_FPS})"
  else
    _fail "Frame rate — expected ${TARGET_FPS}/1, got ${FINAL_FPS}"
  fi

  # Duration bounds
  DUR_OK=$(awk -v d="$FINAL_DUR" -v mn="$MIN_DURATION" -v mx="$MAX_DURATION" \
    'BEGIN{print (d>=mn && d<=mx)?1:0}')
  if [[ "$DUR_OK" == "1" ]]; then
    _pass "Duration ${FINAL_DUR}s is within bounds [${MIN_DURATION}s, ${MAX_DURATION}s]"
  else
    _fail "Duration ${FINAL_DUR}s is outside expected bounds [${MIN_DURATION}s, ${MAX_DURATION}s]"
  fi
else
  _fail "Skipping video spec checks — master audio file not found"
fi

echo ""

# ── Section 4: Audio checks ───────────────────────────────────────────────────
echo "── [4/5] Audio ──────────────────────────────────────────────────────────────"

if [[ -f "$MASTER_AUDIO" && -f "$MASTER_NO_AUDIO" ]]; then
  # _audio.mp4 must have an audio stream
  HAS_AUDIO=$(probe_audio "$MASTER_AUDIO")
  if [[ "$HAS_AUDIO" == "audio" ]]; then
    _pass "DreamPlanet_Master_v1_audio.mp4 has an audio stream"
  else
    _fail "DreamPlanet_Master_v1_audio.mp4 has no audio stream"
  fi

  # _no_audio.mp4 must NOT have an audio stream
  HAS_AUDIO_NA=$(probe_audio "$MASTER_NO_AUDIO")
  if [[ -z "$HAS_AUDIO_NA" ]]; then
    _pass "DreamPlanet_Master_v1_no_audio.mp4 has no audio stream (correct)"
  else
    _fail "DreamPlanet_Master_v1_no_audio.mp4 unexpectedly contains an audio stream"
  fi

  # Audio and video durations must match within tolerance
  if [[ -n "$FINAL_DUR" ]]; then
    AUDIO_DUR=$(ffprobe -v error -select_streams a:0 -show_entries stream=duration \
      -of default=noprint_wrappers=1:nokey=1 "$MASTER_AUDIO" 2>/dev/null || echo "0")
    SYNC_OK=$(within_tolerance "$AUDIO_DUR" "$FINAL_DUR" "$AUDIO_VIDEO_TOLERANCE")
    if [[ "$SYNC_OK" == "1" ]]; then
      _pass "Audio duration (${AUDIO_DUR}s) matches video (${FINAL_DUR}s) within ${AUDIO_VIDEO_TOLERANCE}s"
    else
      _fail "Audio/video duration mismatch: audio=${AUDIO_DUR}s, video=${FINAL_DUR}s (tolerance ${AUDIO_VIDEO_TOLERANCE}s)"
    fi
  fi

  # _audio.mp4 and DreamPlanet_Master_v1.mp4 must have the same duration
  if [[ -f "$MASTER_COMBINED" ]]; then
    COMBINED_DUR=$(probe_format duration "$MASTER_COMBINED")
    MATCH=$(within_tolerance "$COMBINED_DUR" "$FINAL_DUR" "0.1")
    if [[ "$MATCH" == "1" ]]; then
      _pass "DreamPlanet_Master_v1.mp4 duration (${COMBINED_DUR}s) matches _audio.mp4 (${FINAL_DUR}s)"
    else
      _fail "Duration mismatch between _audio.mp4 (${FINAL_DUR}s) and _v1.mp4 (${COMBINED_DUR}s)"
    fi
  fi
else
  _fail "Skipping audio checks — one or more master files not found"
fi

echo ""

# ── Section 5: Scene-level checks ────────────────────────────────────────────
echo "── [5/5] Scene-level checks ─────────────────────────────────────────────────"

WORK_DIR="$REPO_ROOT/tmp_dp_master_build"

# 5a. In quick mode, if the work dir exists from a prior build, verify each
#     normalized scene clip. Skip gracefully if the dir doesn't exist.
SCENES_FOUND=0
SCENES_EXPECTED=${#SCENE_ORDER[@]}

if [[ -d "$WORK_DIR" ]]; then
  for scene in "${SCENE_ORDER[@]}"; do
    norm="$WORK_DIR/${scene}_normalized.mp4"
    if [[ -f "$norm" && -s "$norm" ]]; then
      dur=$(probe_format duration "$norm")
      _pass "Work dir: ${scene}_normalized.mp4 exists (${dur}s)"
      SCENES_FOUND=$((SCENES_FOUND+1))
    else
      _info "Work dir: ${scene}_normalized.mp4 not found (run --full to rebuild)"
    fi
  done

  # 5b. If all normalized scenes are present, verify their durations sum to the master
  if [[ "$SCENES_FOUND" == "$SCENES_EXPECTED" && -n "${FINAL_DUR:-}" ]]; then
    SUM=0
    for scene in "${SCENE_ORDER[@]}"; do
      norm="$WORK_DIR/${scene}_normalized.mp4"
      d=$(probe_format duration "$norm")
      SUM=$(echo "$SUM + $d" | bc)
    done
    SUM_OK=$(within_tolerance "$SUM" "$FINAL_DUR" "$DURATION_SCENE_SUM_TOLERANCE")
    if [[ "$SUM_OK" == "1" ]]; then
      _pass "Scene durations sum (${SUM}s) matches master (${FINAL_DUR}s) within ${DURATION_SCENE_SUM_TOLERANCE}s"
    else
      _fail "Scene duration sum (${SUM}s) does not match master (${FINAL_DUR}s) — a scene may be missing or duplicated"
    fi
  fi
else
  _info "Work dir ($WORK_DIR) not found — skipping normalized-clip checks (run --full to rebuild)"
fi

# 5c. Trim guards — check that no scene's source begins with a near-blank frame
#     after its required trim. This catches the Scene 3 white-gap regression
#     without needing a full rebuild.
TRIM_WORK="$(mktemp -d /tmp/dp_trim_check_XXXXXX)"
trap 'rm -rf "$TRIM_WORK"' EXIT

for scene in "${SCENE_ORDER[@]}"; do
  if [[ -v "TRIM_GUARDS[$scene]" && -v "FLAT_SCENE_SRCS[$scene]" ]]; then
    trim_start="${TRIM_GUARDS[$scene]}"
    src="${FLAT_SCENE_SRCS[$scene]}"
    if [[ ! -f "$src" ]]; then
      _fail "Trim guard ($scene): source not found — cannot perform brightness check: $src"
      continue
    fi
    first_frame="$TRIM_WORK/${scene}_first_frame.png"
    if ffmpeg -y -ss "$trim_start" -i "$src" \
        -vf "select=eq(n\\,0)" -frames:v 1 -update 1 \
        "$first_frame" -loglevel warning 2>/dev/null; then
      brightness=$(convert "$first_frame" -colorspace Gray \
        -format "%[fx:mean]" info: 2>/dev/null || echo "0")
      BRIGHT_OK=$(awk -v b="$brightness" -v t="$BRIGHTNESS_THRESHOLD" \
        'BEGIN{print (b<t)?1:0}')
      if [[ "$BRIGHT_OK" == "1" ]]; then
        _pass "Scene 3 blank-intro guard: first frame brightness ${brightness} < ${BRIGHTNESS_THRESHOLD} ✓"
      else
        _fail "Scene 3 blank-intro guard: first frame after ss=${trim_start} is near-blank white (brightness ${brightness} ≥ ${BRIGHTNESS_THRESHOLD}) — blank-intro regression detected in $(basename "$src")"
      fi
    else
      _fail "Trim guard ($scene): ffmpeg failed to extract first frame from $src"
    fi
  fi
done

echo ""

# ══════════════════════════════════════════════════════════════════════════════
# Summary
# ══════════════════════════════════════════════════════════════════════════════
echo "══════════════════════════════════════════════════════════════════════════════"
TOTAL=$((PASS+FAIL))
if [[ "$FAIL" == "0" ]]; then
  echo " RESULT: ✅ ALL ${TOTAL} CHECKS PASSED"
  if [[ "$MODE" == "quick" ]]; then
    echo " (Quick mode — run with --full to also verify a clean rebuild)"
  fi
  echo "══════════════════════════════════════════════════════════════════════════════"
  exit 0
else
  echo " RESULT: ❌ ${FAIL} OF ${TOTAL} CHECKS FAILED"
  echo ""
  echo " Failed checks:"
  for f in "${FAILURES[@]}"; do echo "   • $f"; done
  echo "══════════════════════════════════════════════════════════════════════════════"
  exit 1
fi
